from odoo import models, fields, api
from odoo.exceptions import UserError, ValidationError
import io
import base64
import xlsxwriter
import json
from datetime import datetime


class SqlReport(models.Model):
    _name = 'custom.sql.report'
    _description = 'Custom SQL Report'
    _inherit = ['mail.thread', 'mail.activity.mixin']

    name =  fields.Selection([
        ('sales_subsidiary_journal_rr9', 'Sales Subsidary Journal RR9'),
        ('sales_journal', 'Sales Journal'),
        ('purchase_subsidiary_journal_rr9', 'Purchase Subsiday Journal RR9'),
        ('purchase_journal', 'Purchase Journal'),
        ('general_ledger', 'General Ledger'),
        ('general_ledger_rr9', 'General Ledger RR9'),
        ('general_journal', 'General Journal'),
        ('general_journal_rr9', 'General Journal RR9'),
        ('disbursement_journal', 'Disbursment Journal'),
        ('cash_receipt_journal', 'Cash Receipt Journal'),
        ('ar_history', 'Account Receivable History'),
        ('ap_by_transaction_date', 'Account Payable by Transaction Date'),
        ('aging_ar', 'Aging of Account Receivable'),
        ('aging_ap', 'Aging of Accout Payable'),
        ('ap_history', 'AP History'),
        ('cancelled_sales_invoice_summary', 'Cancelled Sales Invoice Summary Report'),
        ('cash_collection_summary', 'Cash Collection Summary Report'),
        ('check_collection_summary', 'Check Collection Summary Report'),
        ('deferred_vat_schedule', 'Deferred Vat Schedule'),
        ('depreciation_schedule', 'Depreciation Schedule'),
        ('disbursement_summary_by_date', 'Disbursement Summary Report by Date'),
        ('disbursement_summary_by_series', 'Disbursment Summary Report By Series No.'),
        ('disbursement_summary_detailed', 'Disbursement Summary Report Detailed'),
        ('disbursement_summary', 'Disbursement Summary Report'),
        ('lapsing_schedule', 'Lapsing Schedule'),
        ('or_by_customer', 'Official Receipt Report By Customer'),
        ('or_by_sales_rep', 'Official Receipt Report By Sales Representative'),
        ('or_by_series', 'Official Receipt Report By Series Number'),
        ('or_linked_invoice', 'Official Receipt Report Linked With service Invoice'),
        ('or_summary', 'OR Summary'),
        ('summary_ap', 'Summary of Accounts Payable'),
        ('summary_outstanding_ar', 'Summary of outstanding account receivable'),
        ('summary_outstanding_ap', 'Summary of Accounts outstanding paybale'),
        ('summary_paid_ap', 'Summary of Paid accounts payable'),
        ('summary_released_disbursement', 'Summary of Released Disbursement'),
        ('trial_balance', 'Trial Balance'),
        ('unpaid_sales_invoice_summary', 'Unpaid Sales Invoice Summary Report'),
        ('form_1604e', 'Form 1604E Schedule'),
        ('map_summary', 'MAP Summary  List'),
        ('qap_summary', 'QAP Summary List'),
        ('sawt', 'SAWT'),
        ('semestral_suppliers', 'Semestral List of Regular Supplier'),
        ('vat_summary_purchase', 'Vat Summary List - Purchase'),
        ('vat_summary_sales', 'Vat Summary List - Sales'),
        ('vat_summary_importation', 'Vat Summary List Importation'),
        ('audit_logs', 'Audit Logs'),
        ('form_1900', 'Form 1900'),
        ('secretary_cert', 'Secretary Cert'),
    ], string="Report Name", required=True, unique=True, tracking=True)

    report_category = fields.Selection([
        ('annex', 'Annex'),
        ('books', 'Books'),
        ('other_reports', 'Other Reports'),
        ('tax_returns', 'Tax Returns Mandatory Attachments'),
        ('none', 'None'),
    ], string="Report Category", required=True, tracking=True)

    generated_on = fields.Datetime("Generated On", tracking=True, store=True)
    generated_by = fields.Many2one('res.users', string="Generated By", tracking=True, store=True)

    exported_on = fields.Datetime("Exported On", tracking=True)
    exported_by = fields.Many2one('res.users', string="Exported By", tracking=True)

    description = fields.Text("Description")

    from_date = fields.Date("From Date", required=True)
    to_date = fields.Date("To Date", required=True)

    """ module_id = fields.Many2one('ir.module.module', string="Module") """
    sql_query = fields.Text("SQL Query")
    result_ids = fields.One2many('custom.sql.report.line', 'report_id', string="Results")   

    result_columns = fields.Text("Result Columns")  # store as JSON array

    def action_execute_query(self):
        self.ensure_one()

        # Category books
        if self.report_category == 'books':
            # Sales Subsidiary Journal RR9 Report Query
            if self.name == 'sales_subsidiary_journal_rr9':
                sql = """
                    SELECT 
                        r.vat as "TIN",
                        r."name" as "CUSTOMER CODE",
                        r.complete_name as "CUSTOMER NAME",
                        '' as "DESCRIPTION",
                        a.name as "REFERENCE",
                        a.amount_total as "AMOUNT",
                        '' as "DISCOUNT",
                        a.amount_tax as "VAT AMOUNT",
                        abs(a.amount_total - a.amount_tax) as "NET SALES"
                    FROM sale_order s
                    INNER JOIN account_move a ON s.name = a.invoice_origin 
                    LEFT JOIN res_partner r ON s.partner_id = r.id
                    WHERE a.invoice_date BETWEEN %s AND %s;
                """
            else: 
                raise ValidationError('Please select a valid report.')
        else:
            raise ValidationError("Please select a valid report category.")

        try:
            # ✅ Safe query with parameters
            self.env.cr.execute(sql, (self.from_date, self.to_date))

            columns = [desc[0] for desc in self.env.cr.description]
            rows = self.env.cr.fetchall()

            # Save columns
            self.result_columns = json.dumps(columns)

            # Clear old results
            self.result_ids.unlink()

            # Save results row by row
            for row in rows:
                values = {}
                for col, val in zip(columns, row):
                    if isinstance(val, datetime):
                        val = val.strftime("%Y-%m-%d %H:%M:%S")
                    values[col] = val
                self.env['custom.sql.report.line'].create({
                    'report_id': self.id,
                    'data': json.dumps(values, ensure_ascii=False),
                })

            self.generated_on = fields.Datetime.now()
            self.generated_by = self.env.user

        except Exception as e:
            raise UserError(f"Error executing query: {str(e)}")

    def get_table_data(self):
        """Helper for QWeb to display table"""
        columns = json.loads(self.result_columns or "[]")
        rows = [json.loads(r.data) for r in self.result_ids]
        return columns, rows

    def action_export_excel(self):
        self.ensure_one()
        if not self.result_ids:
            raise UserError("No data to export. Execute a query first.")

        columns = json.loads(self.result_columns or "[]")
        rows = [json.loads(r.data) for r in self.result_ids]

        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output, {'in_memory': True})
        worksheet = workbook.add_worksheet("Report")

        # Header
        header_format = workbook.add_format({'bold': True, 'bg_color': '#D7E4BC'})
        for col, col_name in enumerate(columns):
            worksheet.write(0, col, col_name, header_format)

        # Rows
        for row_idx, row in enumerate(rows, start=1):
            for col_idx, col_name in enumerate(columns):
                worksheet.write(row_idx, col_idx, row.get(col_name, ""))

        workbook.close()
        output.seek(0)

        file_data = base64.b64encode(output.read())
        filename = f"{self.name.replace(' ', '_')}.xlsx"

        attachment = self.env['ir.attachment'].create({
            'name': filename,
            'type': 'binary',
            'datas': file_data,
            'res_model': self._name,
            'res_id': self.id,
            'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        })

        return {
            'type': 'ir.actions.act_url',
            'url': f"/web/content/{attachment.id}?download=true",
            'target': 'self',
        }


class SqlReportLine(models.Model):
    _name = 'custom.sql.report.line'
    _description = 'Custom SQL Report Line'

    report_id = fields.Many2one('custom.sql.report', string="Report", ondelete="cascade")
    data = fields.Text("Row Data")  # store JSON string safely
